[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "biofeedback"
version = "0.1"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.scripts]
cli-name = "biofeedback.controller:run"
